### ISSUE TITLE
`address` attribute of `Credentials` missing? (from documentation)

### ISSUE THREAD

**Issue by cgoliver** [simolus3/web3dart#166]
Hello!

Just trying out this example in the [documentation](https://pub.dev/documentation/web3dart/latest/)

```
import 'package:http/http.dart'; //You can also import the browser version
import 'package:web3dart/web3dart.dart';

var apiUrl = "http://localhost:7545"; //Replace with your API

var httpClient = new Client();
var ethClient = new Web3Client(apiUrl, httpClient);

var credentials = ethClient.credentialsFromPrivateKey("0x...");

// You can now call rpc methods. This one will query the amount of Ether you own
EtherAmount balance = ethClient.getBalance(credentials.address);
print(balance.getValueInUnit(EtherUnit.ether));
```

Of course, I started a Ganache instance and entered a private key that works. 

I get the following error from Flutter:

```
lib/ether_splitter.dart:121:44: Error: The getter 'address' isn't defined for the class 'Future<Credentials>'.
 - 'Future' is from 'dart:async'.                                       
 - 'Credentials' is from 'package:web3dart/credentials.dart' ('../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/web3dart-2.0.0-dev.9/lib/credentials.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'address'.
    var myBalance = getBalance(credentials.address);                    
                                           ^^^^^^^   
```

I am quite new to flutter and dart so I apologize if this is my fault.

Thanks in advance!

**Comment by simolus3** [comment]
Thanks for the report. I think that, instead of `Credentials`, `credentialsFromPrivateKey` should return the more-specific `EthPrivateKey` directly. `EthPrivateKey` does have an `address` getter which you could use then.

As a workaround for now, I'd recommend using:

```dart
import 'package:http/http.dart'; //You can also import the browser version
import 'package:web3dart/web3dart.dart';

var apiUrl = "http://localhost:7545"; //Replace with your API

var httpClient = new Client();
var ethClient = new Web3Client(apiUrl, httpClient);

var credentials = EthPrivateKey.fromHex("0x...");

// You can now call rpc methods. This one will query the amount of Ether you own
EtherAmount balance = ethClient.getBalance(credentials.address);
print(balance.getValueInUnit(EtherUnit.ether));
```

**Comment by simolus3** [comment]
Fixed in f2f24f1f6ea36a651aa81560b713e3b782574984!

**Comment by cgoliver** [comment]
Thanks for the reply! I tried the new suggestion and I still get the same error..

**Comment by simolus3** [comment]
Can you make sure that you're on the latest version (2.1.3)? This works for me.

**Comment by cgoliver** [comment]
yep the upgrade worked, sorry about that!
